### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to load because no supported source was found

### ISSUE THREAD

**Issue by Boscop** [fernandezpaco/video-camera#1]
The demo is not working in Chrome:
> GET https://fernandezpaco.github.io/video-camera/[object%20MediaStream] 404 (Not Found)
> Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by fernandezpaco** [comment]
Fixed, the component was ok, but the demo was outdated.

Thanks for the warning!

**Comment by Boscop** [comment]
Thanks!
Btw, this is exciting:
https://googlechrome.github.io/samples/image-capture/grab-frame-take-photo.html
https://www.chromestatus.com/features/4843864737185792
https://w3c.github.io/mediacapture-image/index.html
Soon it will be possible to give the user more camera controls, for focus, etc.
There's also a polyfill:
https://github.com/GoogleChrome/imagecapture-polyfill

It would be great to have an element for that, with controls for focus etc.
And I guess the next step would be webm video recording?
